/**
 * 立绘内容去重映射：副本路径 → 代表路径（内容相同则共享同一调校记录）。
 * 由脚本自动生成，勿手动编辑。重新生成：npm run portrait:build-canonical
 * 生成时间：2026/9/2 20:21:20（共 56 条）
 */
export const PORTRAIT_CANONICAL_MAP: Readonly<Record<string, string>> = {
    "/assets/SPANISH/__暂留__SPANISH_01.png": "/assets/AMERICA/baiyiya_tuomei.png",
    "/assets/SPANISH/__暂留__SPANISH_02.png": "/assets/AMERICA/eluosi_diguo_bidedadi.png",
    "/assets/SPANISH/__暂留__SPANISH_03.png": "/assets/AMERICA/fodejiao_nuoli.png",
    "/assets/SPANISH/__暂留__SPANISH_04.png": "/assets/AMERICA/foluolida_meinendesi.png",
    "/assets/SPANISH/__暂留__SPANISH_05.png": "/assets/AMERICA/jialebi_bulasilaisuo.png",
    "/assets/SPANISH/__暂留__SPANISH_06.png": "/assets/AMERICA/puxiangyindu_aerbukeerke.png",
    "/assets/SPANISH/__暂留__SPANISH_07.png": "/assets/AMERICA/xingelana_daweila.png",
    "/assets/SPANISH/__暂留__SPANISH_08.png": "/assets/AMERICA/xishudongyin_laijiasipi.png",
    "/assets/SPANISH/__暂留__SPANISH_09.png": "/assets/AMERICA/xiyindu_batuoluomei.png",
    "/assets/SPANISH/__暂留__SPANISH_10.png": "/assets/AMERICA/yasuer_xipuliyanuo.png",
    "/assets/SPANISH/__暂留__SPANISH_11.png": "/assets/AMERICA/zhibuluotuo_enlike.png",
    "/assets/PERSIAN/__暂留__PERSIAN_04.png": "/assets/CENTRAL_ASIA/aba_shapuer.png",
    "/assets/PERSIAN/__暂留__PERSIAN_05.png": "/assets/CENTRAL_ASIA/aqimeinide_daliushi.png",
    "/assets/PERSIAN/__暂留__PERSIAN_06.png": "/assets/CENTRAL_ASIA/gelujiya_tamaer.png",
    "/assets/PERSIAN/__暂留__PERSIAN_07.png": "/assets/CENTRAL_ASIA/kawusi_haidaer.png",
    "/assets/PERSIAN/__暂留__PERSIAN_08.png": "/assets/CENTRAL_ASIA/keerjisi_bagelate.png",
    "/assets/PERSIAN/__暂留__PERSIAN_09.png": "/assets/CENTRAL_ASIA/midi_daiaokaisi.png",
    "/assets/PERSIAN/__暂留__PERSIAN_10.png": "/assets/CENTRAL_ASIA/muer_mujier.png",
    "/assets/PERSIAN/__暂留__PERSIAN_11.png": "/assets/CENTRAL_ASIA/sashan_aerdaxier.png",
    "/assets/PERSIAN/__暂留__PERSIAN_12.png": "/assets/CENTRAL_ASIA/sogdian_dewasitiqi.png",
    "/assets/PERSIAN/__暂留__PERSIAN_13.png": "/assets/CENTRAL_ASIA/wuer_wuernamu.png",
    "/assets/PERSIAN/__暂留__PERSIAN_14.png": "/assets/CENTRAL_ASIA/wulaertu_guo_saerduli.png",
    "/assets/PERSIAN/__暂留__PERSIAN_15.png": "/assets/CENTRAL_ASIA/yisatisi_yisatisi.png",
    "/assets/PERSIAN/__暂留__PERSIAN_01.png": "/assets/CENTRAL_ASIA/__暂留__CENTRAL_ASIA_01.png",
    "/assets/PERSIAN/__暂留__PERSIAN_02.png": "/assets/CENTRAL_ASIA/__暂留__CENTRAL_ASIA_02.png",
    "/assets/PERSIAN/__暂留__PERSIAN_03.png": "/assets/CENTRAL_ASIA/__暂留__CENTRAL_ASIA_03.png",
    "/assets/SOUTHEAST_ASIA/__暂留__SOUTHEAST_ASIA_03.png": "/assets/DIANQIAN/chenla_duyebamo.png",
    "/assets/SOUTHEAST_ASIA/__暂留__SOUTHEAST_ASIA_04.png": "/assets/DIANQIAN/dai_daoyingmeng.png",
    "/assets/SOUTHEAST_ASIA/__暂留__SOUTHEAST_ASIA_05.png": "/assets/DIANQIAN/konbaung_yongjiya.png",
    "/assets/SOUTHEAST_ASIA/__暂留__SOUTHEAST_ASIA_06.png": "/assets/DIANQIAN/kunming_yi_lucheng.png",
    "/assets/SOUTHEAST_ASIA/__暂留__SOUTHEAST_ASIA_07.png": "/assets/DIANQIAN/liaozu_saitatila.png",
    "/assets/SOUTHEAST_ASIA/__暂留__SOUTHEAST_ASIA_08.png": "/assets/DIANQIAN/luchuan_sirenfa.png",
    "/assets/SOUTHEAST_ASIA/__暂留__SOUTHEAST_ASIA_09.png": "/assets/DIANQIAN/medang_panankalan.png",
    "/assets/SOUTHEAST_ASIA/__暂留__SOUTHEAST_ASIA_10.png": "/assets/DIANQIAN/pyu_moluo.png",
    "/assets/SOUTHEAST_ASIA/__暂留__SOUTHEAST_ASIA_11.png": "/assets/DIANQIAN/suke_langanheng.png",
    "/assets/SOUTHEAST_ASIA/__暂留__SOUTHEAST_ASIA_12.png": "/assets/DIANQIAN/ternate_babula.png",
    "/assets/SOUTHEAST_ASIA/__暂留__SOUTHEAST_ASIA_01.png": "/assets/DIANQIAN/__暂留__DIANQIAN_01.png",
    "/assets/SOUTHEAST_ASIA/__暂留__SOUTHEAST_ASIA_02.png": "/assets/DIANQIAN/__暂留__DIANQIAN_02.png",
    "/assets/GERMANIC/yinggelan_hengliwushi.png": "/assets/GERMANIC/__多余__GERMANIC_01.png",
    "/assets/LATIN/__暂留__LATIN_01.png": "/assets/GREEK/__暂留__GREEK_01.png",
    "/assets/LATIN/bosi_puluosi_liukongyishi.png": "/assets/GREEK/__暂留__GREEK_02.png",
    "/assets/LATIN/fujisi_fujiweng.png": "/assets/GREEK/__暂留__GREEK_03.png",
    "/assets/LATIN/kuertaiya_kuertaiya.png": "/assets/GREEK/__暂留__GREEK_04.png",
    "/assets/LATIN/lagoniya_lieaonida.png": "/assets/GREEK/__暂留__GREEK_05.png",
    "/assets/LATIN/maqidun_yalishanda.png": "/assets/GREEK/__暂留__GREEK_06.png",
    "/assets/LATIN/teluoyi_heketuoer.png": "/assets/GREEK/__暂留__GREEK_07.png",
    "/assets/LATIN/__暂留__LATIN_02.png": "/assets/GREEK/__暂留__GREEK_08.png",
    "/assets/LATIN/xilagu_ajiasuokeli.png": "/assets/GREEK/__暂留__GREEK_09.png",
    "/assets/LATIN/yilisi_yifeituosi.png": "/assets/GREEK/__暂留__GREEK_10.png",
    "/assets/LATIN/yipilusi_piluoshi.png": "/assets/GREEK/__暂留__GREEK_11.png",
    "/assets/SLAVIC/bolan_suobiesiji.png": "/assets/SLAVIC/__多余__SLAVIC_04.png",
    "/assets/SLAVIC/kaleiliya_kelimusuoboliefu.png": "/assets/SLAVIC/__多余__SLAVIC_03.png",
    "/assets/SLAVIC/nuowei_halaer.png": "/assets/SLAVIC/__多余__SLAVIC_01.png",
    "/assets/SLAVIC/xiadunhe_siweiyatuosilafu.png": "/assets/SLAVIC/__多余__SLAVIC_02.png",
    "/assets/SPANISH/trastamara_feidinanershi.png": "/assets/SPANISH/__多余__SPANISH_03.png",
    "/assets/STEPPE/__闲置__STEPPE_85.png": "/assets/STEPPE/__多余__STEPPE_02.png"
};
