/**
 * 立绘内容去重映射：副本路径 → 代表路径（内容相同则共享同一调校记录）。
 * 由脚本自动生成，勿手动编辑。重新生成：npm run portrait:build-canonical
 * 生成时间：2026/8/24 23:27:22（共 53 条）
 */
export const PORTRAIT_CANONICAL_MAP: Readonly<Record<string, string>> = {
    "/assets/AFRICA/ethiopia_aizhana.png": "/assets/AFRICA/__多余__AFRICA_02.png",
    "/assets/AFRICA/manding_songdiyata.png": "/assets/AFRICA/__多余__AFRICA_01.png",
    "/assets/AMERICA/aztec_kuaotemoke.png": "/assets/AMERICA/__多余__AMERICA_03.png",
    "/assets/AMERICA/inca_pachakuti.png": "/assets/AMERICA/__多余__AMERICA_02.png",
    "/assets/AMERICA/mapuche_laotaluo.png": "/assets/AMERICA/__多余__AMERICA_04.png",
    "/assets/AMERICA/maya_yasinachang.png": "/assets/AMERICA/__多余__AMERICA_06.png",
    "/assets/AMERICA/muisca_saguamanqika.png": "/assets/AMERICA/__多余__AMERICA_05.png",
    "/assets/AMERICA/tupi_alaliboya.png": "/assets/AMERICA/__多余__AMERICA_01.png",
    "/assets/LINGNAN/__多余__LINGNAN_19.png": "/assets/BASHU/xiang_d_xiangdakun.png",
    "/assets/LATIN/__多余__LATIN_05.png": "/assets/BERBER/buni_hanniba.png",
    "/assets/CENTRAL/huo_songlaosheng.png": "/assets/CENTRAL/__多余__CENTRAL_03.png",
    "/assets/CENTRAL/nanzhong_mazhong.png": "/assets/CENTRAL/__多余__CENTRAL_01.png",
    "/assets/CENTRAL/qian_songjingyang.png": "/assets/CENTRAL/__多余__CENTRAL_02.png",
    "/assets/JIANGNAN/__多余__JIANGNAN_01.png": "/assets/CENTRAL/ruzhou_sunjian.png",
    "/assets/WESTERN/__多余__WESTERN_04.png": "/assets/CENTRAL_ASIA/hali_gedaerzi.png",
    "/assets/INDIA/__多余__india_06.png": "/assets/CENTRAL_ASIA/safawei_d_abasi.png",
    "/assets/WESTERN/__多余__WESTERN_02.png": "/assets/CENTRAL_ASIA/wuhu_dukake.png",
    "/assets/INDIA/__多余__india_07.png": "/assets/CENTRAL_ASIA/xisi_yakubu.png",
    "/assets/TIBET/__多余__TIBET_04.png": "/assets/CENTRAL_ASIA/__闲置__CENTRAL_ASIA_110.png",
    "/assets/WESTERN/__多余__WESTERN_01.png": "/assets/CENTRAL_ASIA/__闲置__CENTRAL_ASIA_110.png",
    "/assets/LINGNAN/__多余__LINGNAN_08.png": "/assets/DIANQIAN/luoyue_zhengce.png",
    "/assets/GERMANIC/bogendi_dadanchali.png": "/assets/GERMANIC/__多余__GERMANIC_03.png",
    "/assets/GERMANIC/keluodiya_zilinsiji.png": "/assets/GERMANIC/__多余__GERMANIC_01.png",
    "/assets/GERMANIC/mazhaer_xiongyati.png": "/assets/GERMANIC/__多余__GERMANIC_04.png",
    "/assets/GERMANIC/safuyi_ameidiao.png": "/assets/GERMANIC/__多余__GERMANIC_02.png",
    "/assets/HEXI/helian_helianbobo.png": "/assets/HEXI/__多余__HEXI_02.png",
    "/assets/HEXI/shizhou_liucong.png": "/assets/HEXI/__多余__HEXI_01.png",
    "/assets/INDIA/gurjara_miqiluobodu.png": "/assets/INDIA/__多余__INDIA_08.png",
    "/assets/JAPAN/beihai_shamusheyun.png": "/assets/JAPAN/__多余__JAPAN_02.png",
    "/assets/JAPAN/yamato_nanmuzhengcheng.png": "/assets/JAPAN/__多余__JAPAN_01.png",
    "/assets/LATIN/baizanting_fulajimier.png": "/assets/LATIN/__多余__LATIN_01.png",
    "/assets/LATIN/baojialiya_asenyishi.png": "/assets/LATIN/__多余__LATIN_03.png",
    "/assets/LATIN/bosi_puluosi_liukongyishi.png": "/assets/LATIN/__多余__LATIN_06.png",
    "/assets/LATIN/saipulusi_juyi.png": "/assets/LATIN/__多余__LATIN_04.png",
    "/assets/LATIN/talanduo_aqita.png": "/assets/LATIN/__多余__LATIN_07.png",
    "/assets/LATIN/yipilusi_piluoshi.png": "/assets/LATIN/__多余__LATIN_02.png",
    "/assets/LINGNAN/funan_fanman.png": "/assets/LINGNAN/__多余__LINGNAN_20.png",
    "/assets/LINGNAN/panyao_pandaxiao.png": "/assets/LINGNAN/__多余__LINGNAN_22.png",
    "/assets/LINGNAN/zhuang_d_washifuren.png": "/assets/LINGNAN/__多余__LINGNAN_11.png",
    "/assets/LINGNAN/__闲置__LINGNAN_22.png": "/assets/LINGNAN/__多余__LINGNAN_21.png",
    "/assets/liuhan/ganzhou_dourong.png": "/assets/liuhan/__多余__liuhan_01.png",
    "/assets/MALAY/malacca_bailimisula.png": "/assets/MALAY/__多余__MALAY_01.png",
    "/assets/SLAVIC/dunhe_tatalinuofu.png": "/assets/SLAVIC/__多余__SLAVIC_01.png",
    "/assets/TIBET/__多余__TIBET_02.png": "/assets/STEPPE/qidan_shulvping.png",
    "/assets/TIBET/__多余__TIBET_01.png": "/assets/STEPPE/__闲置__STEPPE_84.png",
    "/assets/TIBET/faqiang_niechizanpu.png": "/assets/TIBET/__多余__TIBET_08.png",
    "/assets/TIBET/guge_chizhaxichabade.png": "/assets/TIBET/__多余__CENTRAL_ASIA_04.png",
    "/assets/WESTERN/__多余__WESTERN_05.png": "/assets/TIBET/__多余__CENTRAL_ASIA_04.png",
    "/assets/TIBET/kangba_suonuomugunbu.png": "/assets/TIBET/__多余__WESTERN_08.png",
    "/assets/TIBET/nvguo_mojie.png": "/assets/TIBET/__多余__TIBET_09.png",
    "/assets/WEST_ASIA/gulaishi_aibusufuyang.png": "/assets/WEST_ASIA/__多余__WEST_ASIA_02.png",
    "/assets/WEST_ASIA/sumeier_zhajixi.png": "/assets/WEST_ASIA/__多余__WEST_ASIA_01.png",
    "/assets/xianqin/quanrong_yiquhai.png": "/assets/xianqin/__多余__xianqin_01.png"
};
