/**
 * 16 母体文化：全项目「文化属性」的唯一分类轴。
 *
 * 🔴 [2026-09-15 主人定]「文化只有 16 种，就是 16 个建筑风格，不要搞这么乱，
 *    请重新分配 16 文化之间的属性。」
 *
 * 改前的 `GameConfig.CULTURE_COMBAT` 六维表按「文化区」开键，而文化区有 172 个，
 * 表里只填了 29 个，其中 NORTH / EAST 还不是合法区名 —— 实测 **1088 座据点里 603 座
 * 55.4% 的文化区根本不在表内，六维全部静默回落 1.0**，等于一半以上的地图没有文化属性。
 * 现在六维只在这 16 个母体上开键，172 个文化区**全部**经本表归到某个母体，覆盖率 100%，
 * 不存在回落。
 *
 * 16 母体与 16 建筑风格一一对应（见 STYLE_TO_BASE16），也与一级 16 母体文化军团
 * `BASE_16_LEGION_NAMES` 同一套。归属按「该区据点实际用的建筑风格占多数者」定，
 * 无据点的区按母体名前缀归，两者都判不了的 7 个（拜占庭/马其顿/希伦/大希腊/亚马逊/
 * 古典孟加拉/古典先秦）按史实人工指定。
 */
export type Base16Culture =
    | 'CENTRAL' | 'STEPPE' | 'INDIA' | 'GERMANIC'
    | 'PURU' | 'ORIE' | 'LATIN' | 'SLAVIC'
    | 'EAST' | 'PERSIAN' | 'MALAY' | 'GREEK'
    | 'THRACIAN' | 'ANDE' | 'AMERICA' | 'AFRICA';

/** 16 母体，顺序 = 六维表书写顺序，也是审计输出顺序 */
export const BASE16_CULTURES: readonly Base16Culture[] = [
    'CENTRAL', 'STEPPE', 'INDIA', 'GERMANIC',
    'PURU', 'ORIE', 'LATIN', 'SLAVIC',
    'EAST', 'PERSIAN', 'MALAY', 'GREEK',
    'THRACIAN', 'ANDE', 'AMERICA', 'AFRICA',
] as const;

/** 16 母体的中文名，审计与 UI 用 */
export const BASE16_NAMES: Record<Base16Culture, string> = {
    CENTRAL: '东亚', STEPPE: '中亚', INDIA: '印度', GERMANIC: '西欧',
    PURU: '普鲁', ORIE: '中东', LATIN: '地中海', SLAVIC: '东北欧',
    EAST: '东南欧', PERSIAN: '波斯', MALAY: '东南亚', GREEK: '希腊',
    THRACIAN: '色雷斯', ANDE: '安第斯', AMERICA: '中美', AFRICA: '非洲',
};

/** 建筑风格 → 母体，一一对应；据点的 buildingStyle 字段就是它的母体 */
export const STYLE_TO_BASE16: Record<string, Base16Culture> = {
    ASIA: 'CENTRAL', CEAS: 'STEPPE', INDI: 'INDIA', WEST: 'GERMANIC',
    PURU: 'PURU', ORIE: 'ORIE', MEDI: 'LATIN', SLAV: 'SLAVIC',
    EAST: 'EAST', PERSIAN: 'PERSIAN', SEAS: 'MALAY', GREEK: 'GREEK',
    THRACIAN: 'THRACIAN', ANDE: 'ANDE', MESO: 'AMERICA', AFRI: 'AFRICA',
};

/** 文化区 172 个 → 母体 16 个。缺任何一个区都会让它回落 CENTRAL，改区名务必同步这里。 */
export const BASE16_OF_REGION: Record<string, Base16Culture> = {
    // ── 东亚（CENTRAL）· 25 区 ──
    AINU: 'CENTRAL', CENTRAL: 'CENTRAL', DALI: 'CENTRAL', GOJOSEON: 'CENTRAL', GORYEO: 'CENTRAL',
    HEXI: 'CENTRAL', HUAXIA_IMPERIAL: 'CENTRAL', JAPAN: 'CENTRAL', JAPAN_ANTIQUITY: 'CENTRAL', JAPAN_IMPERIAL: 'CENTRAL',
    JIANGNAN: 'CENTRAL', JOSEON: 'CENTRAL', JURCHEN: 'CENTRAL', KHITAN: 'CENTRAL', KOREA: 'CENTRAL',
    MANCHU: 'CENTRAL', MING: 'CENTRAL', MOHE: 'CENTRAL', NANZHAO: 'CENTRAL', NORTHEAST: 'CENTRAL',
    PRE_QIN: 'CENTRAL', QIANG: 'CENTRAL', SONG: 'CENTRAL', TANGUT: 'CENTRAL', VIETNAMESE: 'CENTRAL',
    // ── 中亚（STEPPE）· 28 区 ──
    CENTRAL_ASIA: 'STEPPE', CENTRAL_ASIA_ANTIQUITY: 'STEPPE', CENTRAL_ASIA_CASTLE: 'STEPPE', CENTRAL_ASIA_IMPERIAL: 'STEPPE', CUMAN: 'STEPPE',
    HEPHTHALITES: 'STEPPE', HUNS: 'STEPPE', ILKHANATE: 'STEPPE', KARA_KHITAN: 'STEPPE', KHAZARS: 'STEPPE',
    KUSHAN: 'STEPPE', PASHTUN: 'STEPPE', ROURAN: 'STEPPE', SCYTHIANS: 'STEPPE', SELJUQ: 'STEPPE',
    SOGDIANS: 'STEPPE', STEPPE: 'STEPPE', STEPPE_ANTIQUITY: 'STEPPE', STEPPE_FEUDAL: 'STEPPE', STEPPE_IMPERIAL: 'STEPPE',
    TIMURID: 'STEPPE', TURKS: 'STEPPE', UIGHUR: 'STEPPE', WESTERN: 'STEPPE', WESTERN_CASTLE: 'STEPPE',
    WESTERN_FEUDAL: 'STEPPE', WESTERN_IMPERIAL: 'STEPPE', WUSUN: 'STEPPE',
    // ── 印度（INDIA）· 10 区 ──
    BENGALIS: 'INDIA', BENGALIS_ANTIQUITY: 'INDIA', DELHI: 'INDIA', GURJARAS: 'INDIA', INDIA: 'INDIA',
    INDIA_CASTLE: 'INDIA', INDIA_FEUDAL: 'INDIA', INDIA_IMPERIAL: 'INDIA', MUGHAL: 'INDIA', SIKH: 'INDIA',
    // ── 西欧（GERMANIC）· 19 区 ──
    ANGLO_SAXON: 'GERMANIC', BRITONS: 'GERMANIC', BURGUNDIANS: 'GERMANIC', CELTS_FEUDAL: 'GERMANIC', CRUSADERS: 'GERMANIC',
    FRANKS: 'GERMANIC', FRENCH: 'GERMANIC', GERMANIC: 'GERMANIC', GERMANIC_CASTLE: 'GERMANIC', GERMANIC_FEUDAL: 'GERMANIC',
    GERMANIC_IMPERIAL: 'GERMANIC', GOTHS: 'GERMANIC', HRE: 'GERMANIC', LOMBARDS: 'GERMANIC', SCOTLAND: 'GERMANIC',
    SWEDISH: 'GERMANIC', TEUTONS: 'GERMANIC', VANDALS: 'GERMANIC', VIKINGS: 'GERMANIC',
    // ── 普鲁（PURU）· 5 区 ──
    PURU: 'PURU', TIBET: 'PURU', TIBET_CASTLE: 'PURU', TIBET_IMPERIAL: 'PURU', YARLUNG: 'PURU',
    // ── 中东（ORIE）· 16 区 ──
    ALMOHAD: 'ORIE', ASSYRIAN: 'ORIE', BABYLON: 'ORIE', BERBER: 'ORIE', EGYPT: 'ORIE',
    HEBREWS: 'ORIE', HITTITES: 'ORIE', MAMLUKS: 'ORIE', NABATAEANS: 'ORIE', ORIE: 'ORIE',
    ORIE_ANTIQUITY: 'ORIE', OTTOMAN: 'ORIE', OTTOMAN_IMPERIAL: 'ORIE', WEST_ASIA: 'ORIE', WEST_ASIA_ANTIQUITY: 'ORIE',
    WEST_ASIA_CASTLE: 'ORIE',
    // ── 地中海（LATIN）· 15 区 ──
    AMERICA: 'LATIN', ARAGON: 'LATIN', ARMENIANS: 'LATIN', CARTHAGE: 'LATIN', CASTILE: 'LATIN',
    GEORGIANS: 'LATIN', IMPERIAL_ROME: 'LATIN', ITALIANS: 'LATIN', LATIN: 'LATIN', LATIN_CASTLE: 'LATIN',
    LATIN_FEUDAL: 'LATIN', LATIN_IMPERIAL: 'LATIN', PORTUGUESE: 'LATIN', SICILIANS: 'LATIN', SPANISH: 'LATIN',
    // ── 东北欧（SLAVIC）· 12 区 ──
    BOHEMIANS: 'SLAVIC', BULGARIANS: 'SLAVIC', LITHUANIANS: 'SLAVIC', MAGYAR: 'SLAVIC', POLES: 'SLAVIC',
    RUS: 'SLAVIC', RUSSIAN: 'SLAVIC', SERBIA: 'SLAVIC', SLAVIC: 'SLAVIC', SLAVIC_CASTLE: 'SLAVIC',
    SLAVIC_FEUDAL: 'SLAVIC', SLAVIC_IMPERIAL: 'SLAVIC',
    // ── 东南欧（EAST）· 2 区 ──
    BYZANTINE: 'EAST', EAST: 'EAST',
    // ── 波斯（PERSIAN）· 5 区 ──
    ACHAEMENIDS: 'PERSIAN', PERSIAN: 'PERSIAN', PERSIAN_CASTLE: 'PERSIAN', SAFAVID: 'PERSIAN', SASANIAN: 'PERSIAN',
    // ── 东南亚（MALAY）· 9 区 ──
    BURMESE: 'MALAY', JAVANESE: 'MALAY', KHMER: 'MALAY', MALAY: 'MALAY', SEASIA_ANTIQUITY: 'MALAY',
    SEASIA_CASTLE: 'MALAY', SEASIA_FEUDAL: 'MALAY', SEASIA_IMPERIAL: 'MALAY', SRIVIJAYA: 'MALAY',
    // ── 希腊（GREEK）· 5 区 ──
    GREEK: 'GREEK', GREEK_MERCENARY: 'GREEK', HELLENIC: 'GREEK', MACEDONIAN: 'GREEK', MAGNA_GRAECIA: 'GREEK',
    // ── 色雷斯（THRACIAN）· 2 区 ──
    AMAZONS: 'THRACIAN', THRACIAN: 'THRACIAN',
    // ── 安第斯（ANDE）· 8 区 ──
    ANDE: 'ANDE', CHIMU: 'ANDE', MAPUCHE: 'ANDE', MUISCA: 'ANDE', SOUTHAM_IMPERIAL: 'ANDE',
    TAIRONA: 'ANDE', TEHUELCHE: 'ANDE', TUPI: 'ANDE',
    // ── 中美（AMERICA）· 4 区 ──
    IROQUOIS: 'AMERICA', MAYANS: 'AMERICA', NORTHAM_IMPERIAL: 'AMERICA', TARASCAN: 'AMERICA',
    // ── 非洲（AFRICA）· 7 区 ──
    AFRICA: 'AFRICA', AFRICA_ANTIQUITY: 'AFRICA', AFRICA_CASTLE: 'AFRICA', AFRICA_IMPERIAL: 'AFRICA', ETHIOPIANS: 'AFRICA',
    GHANA: 'AFRICA', KUSH: 'AFRICA',
};

/**
 * 取某文化区所属母体。未知区兜底东亚，与 `getBase16LegionName` 的兜底同口径。
 * 六维五张表**只许**经本函数取值，别再直接用 region 去索引。
 */
export function toBase16(region: string | null | undefined): Base16Culture {
    if (!region) return 'CENTRAL';
    return BASE16_OF_REGION[region] ?? 'CENTRAL';
}
